### ISSUE TITLE
Убрать ненужные импорты

### ISSUE THREAD

**Issue by itigancov** [JohnJoy665/rv-privilege#2]
Сейчас в компонентах встречается такой импорт - `import React from 'react'` 
Например:
https://github.com/JohnJoy665/rv-privilege/blob/2fa3ae757d2dfee28094668d83ebcdf0fca00270/src/components/Card/Card.tsx#L1

С 17 версии реакта такой импорт делать необязательно.
Подробнее можно почитать тут - https://ru.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports

**Comment by JohnJoy665** [comment]
ok
